fix how to register a new user
gothinkster/realworld pull request #617
Opened 2021-02-28 06:43 UTC by GeraldLoeffler

To register a new user POST to `/users` not to `/user`.

2021-04-02 04:02 UTC, thebearingedge requested changes

2021-04-02 04:02 UTC, thebearingedge commented on api/swagger.json
> +    }
There appears to be a comma missing here.

2021-04-09 13:58 UTC, GeraldLoeffler reviewed
missing comma added

2021-04-09 14:00 UTC, GeraldLoeffler commented
thank you @thebearingedge , and sorry for the hickup: should be good now

2021-04-20 00:39 UTC, geromegrignon commented
Thanks for your contribution.
However it's a breaking change for all existing implementations.

To address such issue, your goal is to work on a V2 of the current specs.
Based of these new specs, we'll open the submission of a new generation of implementations.
The current version of the spec will remain unchanged.

We'll track this issue with #626.

2021-04-20 00:39 UTC, closed without merging